NUMPY

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.



NumPy stands for Numerical Python.



In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.



The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.



In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
##Check how many dimensions the arrays have:

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [ ]:
import numpy as np  ## np is alias

## Create array using numpy
## Create 1D Array

arr1=np.array([1,2,3,4,5])  # np.array is fuction to create array 

print(arr1)

print(type(arr1))

print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
## 1D Array
arr2 =np.array([4,5,6,7,8])

## 2D Array
arr2.reshape(1,5)  ## 1 row aur 5 columns   


array([[4, 5, 6, 7, 8]])

In [3]:
# Higher Dimensional Arrays

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [5]:
# Access 3-D Arrays

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


6


In [14]:
# NumPy Array Copy vs View


import numpy as np

arr = np.array([1, 2, 3, 4, 5])  
x = arr.copy()
arr[0] = 42

print(arr)
print(x)


y = arr.view()
arr[0] = 41

print(arr)
print(y)



[42  2  3  4  5]
[1 2 3 4 5]
[41  2  3  4  5]
[41  2  3  4  5]


In [ ]:
## find row and column

arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [6]:
## 2D Array
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
arr2.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [ ]:
## arange is a function in the NumPy library that generates arrays with evenly spaced values within a defined interval.

np.arange(0,10,2).reshape(5,1)   

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
## identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
## Attributes of Numpy Array
import numpy as np
arr =np.array([[1,2,3],[4,5,6]]) 

print("Array :\n",arr)
print("Shape:",arr.shape)
print("Number of dimensions:",arr.size)
print("Size (number of element ):",arr.size)
print("Data type:",arr.dtype)
print("Item size (in bytes):",arr.itemsize) 

Array :
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 6
Size (number of element ): 6
Data type: int64
Item size (in bytes): 8


In [5]:
## Numpy Vectorized Operation
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## Element Wise addition
print("Addition:",arr1+arr2)

## Element Wise Subtraction
print("Sustraction:",arr1-arr2)


## Element Wise mutiplication
print("Multiplecation:",arr1*arr2)

## Element Wise division
print("Division:",arr1/arr1)

Addition: [11 22 33 44 55]
Sustraction: [ -9 -18 -27 -36 -45]
Multiplecation: [ 10  40  90 160 250]
Division: [1. 1. 1. 1. 1.]


In [3]:
## Universal Fuction
import numpy as np
arr=np.array([2,3,4,5,6])
## squre root 
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Since 
print(np.sin(arr))

## Natural log
print(np.log)

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
<ufunc 'log'>


In [ ]:
# # Converting Data Type on Existing Arrays

# Change data type from float to integer by using 'i' as parameter value:


import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(arr.astype(bool))

print(newarr)
5
print(newarr.dtype)



[ True  True  True]
[1 2 3]
int64


Multi-dimensional Arrays:

For multi-dimensional arrays, indices for each dimension are provided, separated by commas (e.g., array[row_index, column_index]).


Slicing uses the format [start:stop:step].


In [ ]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[2:6])    # Output: [2 3 4 5] (elements from index 2 up to, but not including, index 6)
print(arr[:5])     # Output: [0 1 2 3 4] (elements from the beginning up to, but not including, index 5)
print(arr[5:])     # Output: [5 6 7 8 9] (elements from index 5 to the end)
print(arr[::2])    # Output: [0 2 4 6 8] (every other element, with a step of 2)

# Use the minus operator to refer to an index from the end:


print(arr[::-1])   # Output: [9 8 7 6 5 4 3 2 1 0] (reverses the array)

[2 3 4 5]
[0 1 2 3 4]
[5 6 7 8 9]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [2]:
import numpy as np
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(matrix[:2, 1:3]) # Output: [[2 3], [6 7]] (first two rows, columns from index 1 to 2)
print(matrix[1, :])   # Output: [5 6 7 8] (selects all elements in the second row)
print(matrix[:, 2])   # Output: [ 3 7 11] (selects all elements in the third column)


[[2 3]
 [6 7]]
[5 6 7 8]
[ 3  7 11]


In [ ]:
## Array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array :\n",arr)



Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:

arr[0][0]

np.int64(1)

In [13]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [17]:
arr[1:,2]

array([ 7, 11])

In [ ]:
arr[1: ]=100
print(arr)

[  0 100 100 100 100 100 100 100 100 100]


In [3]:
import numpy as np

## statistical concepts--Normalization
## to Have a mean of 0 and standard deviation  of 1
data =np.array([1,2,3,4,5])

## Calculate the mean and standard deviation
mean=np.mean(data)
std_dev=np.std(data)

# Normalize the data  
normalized_data=(data-mean)/std_dev
print("Normalized data :",normalized_data)

Normalized data : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

## Mean
print(np.mean(data))

## Median
print(np.median(data))

## std
print(np.std(data))

## Variance
print(np.var(data))

5.5
5.5
2.8722813232690143
8.25


In [ ]:
## Logical Operator 
data=np.array([1,2,3,4,5,6,7,8,9,10])
data([data>5])

array([ 6,  7,  8,  9, 10])